### ISSUE TITLE
Deployment problem

### ISSUE THREAD

**Issue by alexandrenegreira** [prefapp/prefapp-helm#14]
When I try to deploy my application helm gives me this error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0]): unknown field "pathType" in io.k8s.api.networking.v1beta1.HTTPIngressPath, ValidationError(Ingress.spec.tls): invalid type for io.k8s.api.networking.v1beta1.IngressSpec.tls: got "map", expected "array"]
```

**Comment by alexandrenegreira** [comment]
The problem is that on this line an object is declarated but need to be an array

 https://github.com/prefapp/prefapp-helm/blob/82a6269ed43247dfd4ed9b92ac9296ebd474f990/templates/_renders_ingress.yaml#L19

**Comment by frmadem** [comment]
@alexandrenegreira ok it seems that we need to validate before rendering the ingress tls.

**Comment by alexandrenegreira** [comment]
Anoher problem:

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): unknown field "pathType" in io.k8s.api.networking.v1beta1.HTTPIngressPath

**Comment by frmadem** [comment]
@alexandrenegreira you are right, that feature is for k8s [v1.19](https://kubernetes.io/docs/concepts/services-networking/ingress/).

**Comment by frmadem** [comment]
> @alexandrenegreira ok it seems that we need to validate before rendering the ingress tls.

It has been established on this [PR](https://github.com/prefapp/prefapp-helm/pull/15).

**Comment by frmadem** [comment]
> Anoher problem:
> 
> Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): unknown field "pathType" in io.k8s.api.networking.v1beta1.HTTPIngressPath
> 
> https://github.com/prefapp/prefapp-helm/blob/82a6269ed43247dfd4ed9b92ac9296ebd474f990/templates/_renders_ingress.yaml#L41

I created this [PR](https://github.com/prefapp/prefapp-helm/pull/16) that solves that problem.

**Comment by alexandrenegreira** [comment]
If we want to use future kubernetes versions, we need to change networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

**Comment by frmadem** [comment]
> If we want to use future kubernetes versions, we need to change networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

@alexandrenegreira I've just bumped to version 0.0.3 that deals with this problem with k8s up from 1.19+
