### ISSUE TITLE
Int value renders a wrong output

### ISSUE THREAD

**Issue by arvegadev** [prefapp/prefapp-helm#171]
#### Issue description

When you want to set an int value in a values.yaml in your repo state, helm will render a wrong value.

#### Steps to reproduce the issue

1.  Go to repo state, set an int value in configmap values to use within helmfile
> 
>  ![image](https://user-images.githubusercontent.com/91343444/153894265-ae460bfd-2f17-46f2-9d2d-6a60e7de670d.png)
>  
>  ![image](https://user-images.githubusercontent.com/91343444/153894073-61ebdfd3-24c9-4c45-a228-602a26b236b4.png)

 
2. Run helmfile template
```bash
helmfile -e pro template  

```

#### What's the expected result?

![image](https://user-images.githubusercontent.com/91343444/153895366-0b165c95-5c3c-433f-ba94-8d9a6602ed5f.png)

#### What's the actual result?

![image](https://user-images.githubusercontent.com/91343444/153894934-021eb7c2-1e05-453e-a51f-4919656f4532.png)

**Comment by frmadem** [comment]
@arvegadev  I don't think this is a bug or an issue. The thing is profile_id is not an integer but a string. The internal representation of an integer heavily depends on go (which is the interpreter at the heart of Helm). 

In the values file you should express your profile_id with quotes.
