### ISSUE TITLE
HPA deprecated API kubernetes 1.26

### ISSUE THREAD

**Issue by o-iglesias** [prefapp/prefapp-helm#204]
Hello,

It's not possible to use the HPA (Horizontal Pod Autoscaler) render in Kubernetes 1.26 as the API version it utilizes, autoscaling/v2beta2, is no longer available in this version of Kubernetes. You will need to update the API version in the HPA configuration to autoscaling/v2 to make it compatible with Kubernetes 1.26.

For additional details, you can refer to the Kubernetes documentation on API deprecation: [Kubernetes API Deprecation Guide for version 1.26](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26).

**Comment by frmadem** [comment]
@o-iglesias with this #205 it should be fine.
